<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Negative Case</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e2ef970d-726e-494c-af05-a9c32e4b1fa6</testSuiteGuid>
   <testCaseLink>
      <guid>673dd031-87b0-4919-833c-b72b884e33f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login No Input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e402aadd-7f6c-450e-8f66-451edf610fc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deaffdfa-823f-4a3e-999b-0e91e5f7a810</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d488b76-3db2-4115-9ddd-64c68b3d5f8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login Usr tidak diinput</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e15f14ff-bc64-4bb3-a210-2e558c4a5a9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e8ccaba-0cf1-4e8c-97d7-823e91e5ca56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0549912f-9d0e-46dc-8b47-bdf4ba07ce59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login Pw tidak diinput</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6902b6f0-0c43-4aa3-910c-d6f7cc8190bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>103f2e96-a80a-4645-94d0-39b1c9df1161</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bbf2d0b-8a65-4eb0-8738-ed2bf1ebf770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login Incorrect Usr</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a8e63e0-5900-4405-b170-d6a14cdcc88d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81925e01-ea83-404d-95b2-c7cace3c7019</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cef05117-78c0-435f-9eb0-760aaacee21b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login Incorrect Pw</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5f4161b-e3ec-4a98-8996-e164e9762730</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d054aa2e-441b-4ae6-ab84-fae4ce6f331c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a898c7aa-eccd-434d-803e-c03953a61225</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Login MAdmin/Negative Case PGAdmin/Login Incorrect Usr n Pw</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d53ac13-b01a-4e0a-bf93-4354e6b4d096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29d8f489-f265-406f-bef0-9473aadd0eaa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
