<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MAdmin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>501fa47e-2b1f-4632-a997-8ec53b38a497</testSuiteGuid>
   <testCaseLink>
      <guid>eb3947af-d062-4eff-9393-46f7ca764ee4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Merchant</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e614e89-5765-4c7c-9334-9e49fb242474</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b273b08-90ed-49d5-9982-df874b45fedc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fe2a03d-ee86-4bd2-b2ba-c67f61622411</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c30a8b2-02ea-44e2-8862-ba7a2720b05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eea35eef-c038-400b-bba0-24b8067d3000</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a8ef29b-3781-4e36-8515-e050124fdbb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Form Date</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61858bb8-17e9-495c-a18b-5c72e5b0dd89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce78a720-8422-404b-85e6-a16e1303ca7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c239cbb6-3bce-43e6-a37e-89a4084c4920</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - To Date</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb48dc6-5159-4c03-8e5c-5a57a12fdbd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c803477c-ca10-48a2-b3a7-bef59f9aee4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a495fad2-25c6-42df-8b30-eca29da04cdc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Payment Method</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99e67e5-c8c8-4d73-9673-afd9bfd50945</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8184ccbb-528f-4fe6-8b65-30693ec83949</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5fe55be-078a-4923-abbf-a1ef16fbd5d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Payment Provider</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe08582-9e37-4cf0-9671-7f4b1238a14b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd5e25e-f240-451c-bec1-f7a2de240a83</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10efea07-29fc-4e99-bfd1-494863508f8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Monitoring/Monitoring - Search Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08ac462-053a-484a-9de8-10e2d8f6d5c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4375464-9fdb-4f08-8dac-710a5fd063fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f94251e5-9bc3-4d99-aa25-a84a661c44d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - View Merchant</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b0b9f1-28db-44d0-90aa-f003a95d9621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3beff55c-008d-4803-b041-83f2234c0c03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>297e587b-03bd-4d5d-8617-6f2c700e684d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>046cce07-f90d-4d16-84d0-f194d5938f8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcfdb3b7-62bc-4776-b597-8cd86c08b08f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b5f2c98-7ca2-4f3b-aa77-9457a71c5417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Binlist)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5c6b31f-4231-4551-997e-1898056ca8fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1267d475-6af0-4758-ad49-3c09b98ab319</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>952601f7-931b-4917-862e-7f1b9be569e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Countrylist)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6761ce33-3b22-4afa-a803-e42a48f32fc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e61979-202e-4f0d-a6b3-75b7ecccd3d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fd3e6a1-7d94-46fd-803a-5258c232dfcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Domestic)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73115f35-7119-4e8b-8151-8f8eb9a0eb28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42005bf1-c290-4806-b6ac-ac9eeea5e85f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a83bd45c-e418-4500-b6e9-57084cae8487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Maximum PAN velocity)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9130242e-fad6-46e7-9d4f-3e1f87c71de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94629197-3540-4a12-9a43-187de9e00763</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afb1581b-096f-4fbc-81fa-2a424913b9b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Maximum transactions velocity)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44660f4a-1b6b-4adc-8ad2-eab0226c9977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ece5d92-383d-4311-991a-31d26d617459</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87fcfdbe-449f-47d3-947a-0de47abad909</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(Merchant Tip)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27ab9587-27ed-4d36-89b9-907695d10a3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bcfe4c0-479c-4fcb-9939-71133d52eeea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bab9201b-0c31-4a32-bff1-9731b1ca8d94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(PAN burst)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e233a7c-6094-4856-8bc8-b0ff59a6afd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdb02b40-3a23-4023-b708-826ddfbc2935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19f90998-82e7-41c8-81a4-f12343c94a1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(API Burst)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed6bf1a0-a23f-4886-b3ad-f2f71b82d395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>923c544f-2479-4b5b-8df0-e67c4be27ecc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>288ac36d-00c7-4e43-a3b6-3119b4a5e762</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Postgre/Testcase Detail/MAdmin/Velocity Monitoring/Velocity - Velocity Type(3DS)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eea4565d-9b99-448e-bd82-c801249ce016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11e2af0e-1d87-44e9-8cdc-9a1a6727e872</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
