<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MTIISO Purchase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9cc04bf1-8e84-4113-b1e1-e2ab23bbf9e0</testSuiteGuid>
   <testCaseLink>
      <guid>709c2cc1-4652-4469-b187-b897e8677c8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase Visa on us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c9278df-4742-4fc8-a022-64c6c84246a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cecf2874-5bf5-4a92-badc-9561d8a8395d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11409840-71b8-4c34-9d56-e5da33e1f3fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7fc1089-131c-41f2-a437-79756c9c266c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase Visa off us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6cc6eef-67a2-4f0a-bb2d-1220517949d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b84229-abf8-4e34-b0c3-f2ecf95403fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ec2355-d801-493c-a505-6376f356046a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73db639f-66f3-4b17-ace1-b9630c4f8231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase Master on us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>976ee9e2-3c38-4cba-8dc7-e7f817694cef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2400a436-70cc-49f2-99b9-59aa1966ef59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a4d081-983a-4895-9e72-1d785e7269ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5becc6ee-110c-4a13-9b57-f99039b4a383</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase Master off us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd8f20fe-8aef-458b-9a51-bad869978914</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c7d45d3-a1e3-48d4-9cf0-de1982231382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d61aeb0f-8094-47f7-9674-81518b9a959f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90c4b96e-dbfc-4e3b-b14b-82836ac2dd21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase JCB on us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cfa0373-d520-4491-aa8d-b3cc9cd94951</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7acbd4fe-6c19-419e-afc5-07a0e1ac8047</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd3bb257-9094-42dc-a952-690cba4ae605</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddb0fa21-1adc-433a-9ebc-b18f2a2863fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Testcase Scenario/Purchase-Regular Sale/MTIISO/MTIISO Purchase JCB off us</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3416aae2-195d-41ca-a552-0417dabd8269</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d82744e-baf4-415e-bbd0-49e422e67cf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ddef178-d858-4256-9e50-baaeae9657e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7d06d29-87a5-49c1-87f2-c3045b3fe58f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
