<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_6Bulan Cicilan</name>
   <tag></tag>
   <elementGuidId>0e4c1021-933a-4a76-b50e-4525680b28b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paper']/form/div/div[5]/div/div/button[3]/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87907f0f-e331-47e7-b318-3973f4b9d398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>9f8af34a-4abd-4bb1-880d-b12473e70755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6Bulan Cicilan</value>
      <webElementGuid>7b80b798-5a2c-4c81-b8a0-c2d7e4d38fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paper&quot;)/form[1]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-12&quot;]/div[@class=&quot;installment columns&quot;]/div[@class=&quot;MuiToggleButtonGroup-root toggle-button-group&quot;]/button[@class=&quot;MuiButtonBase-root MuiToggleButton-root MuiToggleButtonGroup-grouped plan&quot;]/span[@class=&quot;MuiToggleButton-label&quot;]/div[@class=&quot;month&quot;]</value>
      <webElementGuid>ca992684-454c-4cb8-aff1-0578df6c4817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paper']/form/div/div[5]/div/div/button[3]/span/div</value>
      <webElementGuid>b9919a89-2ca6-4fef-83bc-6df54cf15160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 2,505 / Mo.'])[1]/following::div[1]</value>
      <webElementGuid>d8a6bd44-c6da-456e-a7dc-2ddec3e425fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan Cicilan'])[2]/following::div[2]</value>
      <webElementGuid>c3cdd0ff-32bc-4ccb-afbf-2c025db77072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 1,670 / Mo.'])[1]/preceding::div[1]</value>
      <webElementGuid>5b35bd7a-141c-454f-a35f-d0160e86b656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/div</value>
      <webElementGuid>f01bc04e-d309-40f8-8875-38773ab61ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '6Bulan Cicilan' or . = '6Bulan Cicilan')]</value>
      <webElementGuid>9d4870bd-4e54-49dc-8d90-782fa75765d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
