<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MM _ YY</name>
   <tag></tag>
   <elementGuidId>a958502b-ca1c-43c4-82db-c8c0184ddf4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'expiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ecee1bc-f60d-4db1-9385-dca767b056ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5186643-0d48-4d1c-8c79-e9220f6f96fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>9af4d726-eb3b-4cad-acfa-31b92537f7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>bf045262-437e-45f2-be26-5bc41504778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>9a550b46-becc-45b6-b759-ce060568c410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>1ac6bb10-5fa1-4d40-880b-1d7e4d0623aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f4369253-ae06-4a0f-9040-afb7a9670ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expiry date in format MM YY</value>
      <webElementGuid>205ead37-2669-43b3-821c-f5fea5cc0679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input</value>
      <webElementGuid>46970c6e-0700-4257-93cf-198a2dee937e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-55698c3242c2550790318eb173e3cf58</value>
      <webElementGuid>41cd8ace-73d6-4c68-a068-debc7b065501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'expiryDate']</value>
      <webElementGuid>70496117-c80f-4e36-a418-b1796379d523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'expiryDate']</value>
      <webElementGuid>2d790fa9-48f7-46e6-873d-7c629feecbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiryDate' and @name = 'expiryDate' and @placeholder = 'MM / YY' and @type = 'tel']</value>
      <webElementGuid>cdf2fb90-6991-4aba-a19c-06f4c1f6fe1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
