<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kembali</name>
   <tag></tag>
   <elementGuidId>8ca430f2-6681-40f3-ad17-85345fe76a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.MuiButton-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' MuiButton-label ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e7d9194-c009-4ce3-8e98-924f2e5779f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label jss2818</value>
      <webElementGuid>815f16bf-5cfe-4efa-b581-080ef9fe81b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>74471883-66ec-407f-b5f4-d1fd2632a698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c6981eb2f952780d0f04e80340fd20f9</value>
      <webElementGuid>e6492684-882f-4e9a-85ca-53044307aa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' MuiButton-label ')]</value>
      <webElementGuid>0b6b7679-5306-44ee-ab45-01630c97f93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' MuiButton-label ')]</value>
      <webElementGuid>608a6d53-8083-4412-8652-957f739fd833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>9efa088c-f8f7-4a6b-b347-fc323d745036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
