<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_DASHBOARD</name>
   <tag></tag>
   <elementGuidId>2dca95f5-d956-47ee-ae8c-7f98c3978f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.jss64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/nav/div/span/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f7fa326e-f3b3-4af4-aba9-e761743a2eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss64</value>
      <webElementGuid>ea3bae7f-aaab-4b4d-bf39-1f0b4ede8380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DASHBOARD</value>
      <webElementGuid>e5a4408e-c44e-43a7-a86c-32ac645f2f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss38&quot;]/div[@class=&quot;jss39&quot;]/div[@class=&quot;MuiPaper-root jss43 jss40 MuiPaper-elevation1&quot;]/div[1]/nav[@class=&quot;jss50&quot;]/div[@class=&quot;jss62&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-overline&quot;]/div[@class=&quot;jss63&quot;]/p[@class=&quot;jss64&quot;]</value>
      <webElementGuid>db994364-d9b2-4deb-b67a-dbee70ac47cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/nav/div/span/div/p</value>
      <webElementGuid>e9c3aca4-5a11-4ee6-901a-ba7844a8f5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/following::p[1]</value>
      <webElementGuid>c862f0d9-5007-4535-bf2e-ffd8358f0d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::p[2]</value>
      <webElementGuid>a5951169-6723-4fc7-9963-94158761584d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick actions'])[1]/preceding::p[1]</value>
      <webElementGuid>25aa996e-1644-42e8-a7c0-e45522af19fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring'])[1]/preceding::p[1]</value>
      <webElementGuid>556a7539-c2e8-4c21-8398-de220dab0ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DASHBOARD']/parent::*</value>
      <webElementGuid>67e7f4dd-a1d8-409b-9513-b55d5a88e5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/p</value>
      <webElementGuid>216619ff-ee09-4ad7-b47d-ce89bf72c507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'DASHBOARD' or . = 'DASHBOARD')]</value>
      <webElementGuid>b0bbf87b-474d-48e4-b935-0327e29f1247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
