<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3ds - 3DS</name>
   <tag></tag>
   <elementGuidId>d9cbacff-50c1-43ea-bd49-8516019de4fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-39480-option-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-39480-option-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cb13b9e9-f387-413c-b282-c61bec051084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e3982237-032d-4f89-93d4-2aa22e60e0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>81bb4123-2d57-4ab2-b700-e93ef4f8b49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-39480-option-7</value>
      <webElementGuid>608b367a-8433-4132-88bc-8f51ff714057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>8d907251-d423-4c7c-b048-dfd407368264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0eccc6d-1e5f-423d-bd58-ae0097424270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3bb0071d-0ebf-41e6-80e5-345c6a71c941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>8b85fa61-cba1-48b7-940e-a9e7da553d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8d161e3-645a-49bb-ae15-dd71a09364d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3ds - 3DS</value>
      <webElementGuid>ead38b6a-974d-4ee6-b973-29227ac0c0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-39480-option-7&quot;)</value>
      <webElementGuid>4b397e04-77b3-4dfb-abd6-7aa1860d1c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-39480-option-7']</value>
      <webElementGuid>4878aaab-bc2e-4a36-8be0-7833d5f3e8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-39480-popup']/li[8]</value>
      <webElementGuid>868ef36a-9eee-4119-8af9-e7df21cb9657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maxtrxpan - Maximum PAN velocity'])[1]/following::li[1]</value>
      <webElementGuid>12fed692-a9a7-44ef-87a9-01ce2f5cd2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maxtrxmerchant - Maximum transactions velocity'])[1]/following::li[2]</value>
      <webElementGuid>53d3c60c-b601-48fa-9e37-31de9e2a64f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='domestic - Domestic Only'])[1]/preceding::li[1]</value>
      <webElementGuid>2be9a64b-2ec0-43fa-811e-b2884e5f5fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3ds - 3DS']/parent::*</value>
      <webElementGuid>32a1570d-2234-415a-a7e1-a7aa6578c263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[8]</value>
      <webElementGuid>bb2bf8ae-73e8-4cff-a4ee-8d612d458701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-39480-option-7' and (text() = '3ds - 3DS' or . = '3ds - 3DS')]</value>
      <webElementGuid>7c08f87c-15a8-4d0d-b770-47af826aa2b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
