<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>apiburst - Max API call  minutes</name>
   <tag></tag>
   <elementGuidId>f4b942ac-a6b5-4de6-b1e2-00fa72289893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-96634-option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'MuiAutocomplete-option' and (text() = 'apiburst - Max API call / minutes' or . = 'apiburst - Max API call / minutes')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-96634-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>01e27e0c-c830-4ff8-9dce-664d3aaf04fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9296e276-b841-4aee-a717-6fadf5a792e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ae0e7d91-1d4a-4aa2-b191-e0f163eba41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-96634-option-1</value>
      <webElementGuid>1e1b7c94-a80d-4da2-a466-d518b8b6319d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6b60a4cd-7431-4d82-b806-ab755a390264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5beece1-e32d-4d1a-9df9-0aa581b500cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e16236fd-4dcd-4e46-aa1c-95c1f9c43228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>f532f6b4-8a17-489b-8fd1-5e0854b430b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8320eb5-c91c-4ac4-98fb-98bbf4869b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>apiburst - Max API call / minutes</value>
      <webElementGuid>d21ab88b-ce10-41c0-b335-ffecdda6518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-96634-option-1&quot;)</value>
      <webElementGuid>ad526312-5a8f-4aa8-a224-aa09d95f599a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-96634-option-1']</value>
      <webElementGuid>41db6bfd-0a88-41eb-80da-abb786e7e9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-96634-popup']/li[2]</value>
      <webElementGuid>48b986ec-a4bc-46da-a465-2a6ac055eeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='merchantip - Merchant IP validator'])[1]/following::li[1]</value>
      <webElementGuid>5398786b-ffb0-4b08-a553-3af5561581ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='countrylist - Country black list'])[1]/preceding::li[1]</value>
      <webElementGuid>01a76bd0-29d6-4088-9bdd-320cd4fe8c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='binlist - BIN black list'])[1]/preceding::li[2]</value>
      <webElementGuid>a9b8549d-9d20-425c-b47d-70d906df5d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='apiburst - Max API call / minutes']/parent::*</value>
      <webElementGuid>a4be744a-205b-44f5-bea1-94431b2fa4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]</value>
      <webElementGuid>53d3634d-f737-4efe-874f-8351e9810955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-96634-option-1' and (text() = 'apiburst - Max API call / minutes' or . = 'apiburst - Max API call / minutes')]</value>
      <webElementGuid>5b9fd2a8-882b-48d0-afb2-72b6e89d6ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
