<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>countrylist - Country black list</name>
   <tag></tag>
   <elementGuidId>f4829bd8-a16d-48bc-a7a4-31d3191617be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-39480-option-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-39480-option-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4a987cb7-defc-44aa-9533-2050a14fe7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>addd9ac3-8af0-4311-bfe4-b1a45311cb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3fd9d995-0ac8-4214-872c-12093e9cd4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-39480-option-2</value>
      <webElementGuid>8c094514-498d-42dd-b400-4bc991d3340d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0896b71e-579c-46c6-9d50-a0d785c59037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7032f49-9e5d-494e-85c2-20cca0092315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>133af444-7d8c-4937-8907-81b7910fbbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>4839c0c4-4584-4947-b3f4-6cb2eec08038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ee60991-6f6d-4165-8a51-7356c698f8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>countrylist - Country black list</value>
      <webElementGuid>80391b92-a8b0-4345-8e99-62557997d596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-39480-option-2&quot;)</value>
      <webElementGuid>f7c747d3-3fc7-4b21-8b0d-217b62018f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-39480-option-2']</value>
      <webElementGuid>eb86a969-0861-41f3-8730-119eab0f376d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-39480-popup']/li[3]</value>
      <webElementGuid>9c532cd1-ed72-4939-a4fb-be20819b6272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apiburst - Max API call / minutes'])[1]/following::li[1]</value>
      <webElementGuid>2832a771-6241-492f-b0f2-644f7b17a6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='merchantip - Merchant IP validator'])[1]/following::li[2]</value>
      <webElementGuid>19c4abe9-7099-4634-976d-9667d949f7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='binlist - BIN black list'])[1]/preceding::li[1]</value>
      <webElementGuid>e55f1ae8-46f6-4c1c-82fe-29a4cd588566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panburst - PAN Burst'])[1]/preceding::li[2]</value>
      <webElementGuid>0aa4147f-54a1-4dfb-a356-725d29c234b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='countrylist - Country black list']/parent::*</value>
      <webElementGuid>d10efcea-4611-4ba5-8e47-4e5bb9da2628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]</value>
      <webElementGuid>fa2e949c-3df2-4dae-8307-831f4bee821f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-39480-option-2' and (text() = 'countrylist - Country black list' or . = 'countrylist - Country black list')]</value>
      <webElementGuid>8fab9ef8-8cc1-4fd4-9da4-0e87a80ada24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
