<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>maxtrxmerchant - Maximum transactions velocity</name>
   <tag></tag>
   <elementGuidId>1a9513f2-e394-444e-b7d9-ee3e9e045bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-39480-option-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-39480-option-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3a42b849-46a8-482c-a504-d96810744067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3fa97d8e-fee5-4809-b87f-f44821e6a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8d105819-aaa7-4b39-9d9c-b116dd7ae086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-39480-option-5</value>
      <webElementGuid>d4ac236e-9077-4fe8-840b-f588b175d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>18aca835-6009-4684-bcce-c820e6e01095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5adf4b9-c853-41b4-9ae3-d004e984ad78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b45de22-74fc-4105-a1fa-04478e23adbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>98f3064c-5f66-45b1-b854-e53315ac07c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81162a61-d930-46d6-b697-7ecce5bd07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>maxtrxmerchant - Maximum transactions velocity</value>
      <webElementGuid>ed37ddcd-b245-4a29-982e-fe55686483d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-39480-option-5&quot;)</value>
      <webElementGuid>1e922dfa-32d2-4e81-9b79-1104817683fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-39480-option-5']</value>
      <webElementGuid>91573704-e126-416a-93c1-8bb51a2bb581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-39480-popup']/li[6]</value>
      <webElementGuid>1604cb4c-72ba-40fc-a1ed-ae0d196bc5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panburst - PAN Burst'])[1]/following::li[1]</value>
      <webElementGuid>386be38a-cd80-4423-a232-5590c35ad37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='binlist - BIN black list'])[1]/following::li[2]</value>
      <webElementGuid>6c5652a1-48c2-41cc-8f23-7753471e7ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maxtrxpan - Maximum PAN velocity'])[1]/preceding::li[1]</value>
      <webElementGuid>e81d645c-580f-4c72-a185-1d43cc20fdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='domestic - Domestic Only'])[1]/preceding::li[3]</value>
      <webElementGuid>ede50c1c-3f24-44e4-ac4e-78d093b7c136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='maxtrxmerchant - Maximum transactions velocity']/parent::*</value>
      <webElementGuid>78131879-59e7-40ae-806f-f83269523611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[6]</value>
      <webElementGuid>1aef89ca-b131-48e0-bf96-23394aa4ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-39480-option-5' and (text() = 'maxtrxmerchant - Maximum transactions velocity' or . = 'maxtrxmerchant - Maximum transactions velocity')]</value>
      <webElementGuid>f1f836ce-d3a2-49e1-8eb5-048ab10cdcad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
