<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>merchantip - Merchant IP validator</name>
   <tag></tag>
   <elementGuidId>ad64f2ca-ffcf-4757-8907-5b9fd7298973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-96634-option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'MuiAutocomplete-option' and (text() = 'merchantip - Merchant IP validator' or . = 'merchantip - Merchant IP validator')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-96634-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>513486f7-aa4c-4562-a28c-3a8f33d22863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>afecaf75-9d76-4a55-b022-80d37cf42af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a9910708-d758-4136-9594-adc89daaa95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-96634-option-0</value>
      <webElementGuid>82647630-a5b5-4685-9676-e9dece226d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49f5bcb8-2fae-4712-a469-17bde523d4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1000d25e-6edb-43c8-90bc-90729f7552f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>faa04b4a-8a18-4bac-8364-b1209217a7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>d55a7f3b-9a8b-4464-868d-81bfcd2be1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e2e6be1-4bda-44e6-9322-f9e87203a988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>merchantip - Merchant IP validator</value>
      <webElementGuid>b20ee59b-fd0c-4c8b-a7a9-59702279e476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-96634-option-0&quot;)</value>
      <webElementGuid>05b09645-4168-4f08-8b8a-9bd8a599fcae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-96634-option-0']</value>
      <webElementGuid>48833f07-8788-463f-8919-5f58a3d02dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-96634-popup']/li</value>
      <webElementGuid>b850b530-ff1e-4edb-be3d-055ae0629fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>73a12097-b9f7-4c63-bf0b-f5a460dac2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='apiburst - Max API call / minutes'])[1]/preceding::li[1]</value>
      <webElementGuid>3fb0ab53-7890-4376-9116-786553520c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='countrylist - Country black list'])[1]/preceding::li[2]</value>
      <webElementGuid>a4dbef8c-79a8-4633-a11b-382d2e374f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='merchantip - Merchant IP validator']/parent::*</value>
      <webElementGuid>ea01f5b7-c3b4-461c-b595-0eefb19a75bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>1835e298-bd97-4b8a-a9f4-410a9cd7a2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-96634-option-0' and (text() = 'merchantip - Merchant IP validator' or . = 'merchantip - Merchant IP validator')]</value>
      <webElementGuid>f7d56d3f-603c-431c-a767-fa2d08534c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
