<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>panburst - PAN Burst</name>
   <tag></tag>
   <elementGuidId>01c65450-e89b-4ecd-aefd-8dd9e9f3dc09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-39480-option-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-39480-option-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c3987a43-13f7-447d-9d11-af56f5af922e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>545c0b30-0ace-475a-b691-ae48cbbb0bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3873ee94-3cad-4238-845b-7c35cc6c21f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-39480-option-4</value>
      <webElementGuid>fce93c31-076d-48bb-a535-07a1a3ef837f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>497ae7f3-1cdd-48b9-a073-cc8d273599e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>49076a3a-d1b5-4f99-a8c8-6ff0bdded051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>03b2ec0c-cac4-4091-ab6b-ea286550f95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>0eb616b7-3bdb-4f9e-b311-fadeb1646cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf3209c4-d74d-47ba-92ef-91b00691532f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>panburst - PAN Burst</value>
      <webElementGuid>b27845bf-77b1-4587-840d-28f4cf47c055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-39480-option-4&quot;)</value>
      <webElementGuid>240e3858-f779-42ac-89e6-80ae95dd9f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-39480-option-4']</value>
      <webElementGuid>f9792a4d-01e2-4ac7-a53b-5a0991068158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-39480-popup']/li[5]</value>
      <webElementGuid>5fec9b4b-faa6-45b5-9409-830f1950f7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='binlist - BIN black list'])[1]/following::li[1]</value>
      <webElementGuid>5d42e374-508a-4e37-ac7a-e77f8a5f1298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='countrylist - Country black list'])[1]/following::li[2]</value>
      <webElementGuid>e031ebe1-5e5b-46b3-b37e-ccd4e124421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maxtrxmerchant - Maximum transactions velocity'])[1]/preceding::li[1]</value>
      <webElementGuid>a28d8c72-71f0-4f25-8160-c14ef858854c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maxtrxpan - Maximum PAN velocity'])[1]/preceding::li[2]</value>
      <webElementGuid>0cd551ae-54a0-462a-bb39-9111bdc3883a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='panburst - PAN Burst']/parent::*</value>
      <webElementGuid>ca10425d-9ad7-4cd1-ab3c-632ffbd05cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[5]</value>
      <webElementGuid>65f1e3cc-a66e-4ca7-a07b-450b587edbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-39480-option-4' and (text() = 'panburst - PAN Burst' or . = 'panburst - PAN Burst')]</value>
      <webElementGuid>a5997bcc-46b0-428a-959c-b2d102b72c53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
